# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run notification
# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/5 * * *'

  pull_request:
    branches:
      - main

  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      env:
        BOT_ID: ${{ secrets.BOT_ID }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        ANIO: ${{ secrets.ANIO }}
        EXPEDIENTE_ID: ${{ secrets.EXPEDIENTE_ID }}
      run: |
        python3 main.py
    # Runs a set of commands using the runners shell 
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: git pull
      run: |
          git pull origin master

    - name: git add
      run: |
          git add -A
          ls -la

    - name: commit & push
      run: |
          git diff-index --quiet HEAD || git commit -m "Actualizado ${{ github.event.repository.updated_at}}"
          git push
